### ISSUE TITLE
UI Tweak: CSS

### ISSUE THREAD

**Issue by EkoOne** [modmore/VersionX#107]
This is admittedly (very) small stuff but it jumped out at me nevertheless. I've included a [screenshot in this Dropbox link](https://www.dropbox.com/s/pue6xwwaflh0m01/modx_version_x.png?dl=0).

- The "VersionX" heading is flush to the left and not indented slightly like every other MODX heading.
- The "Resource" field is shorter than the other fields.
- A little vertical space between the fields would be helpful.
_(A couple clients have mentioned that the "stacked" appearance looks like one big field.)_

**Comment by muzzwood** [comment]
VersionX 3.x is a complete rebuild so this shouldn't be an issue anymore :)
Closing!
