### ISSUE TITLE
Feature request: Log when resource is deleted

### ISSUE THREAD

**Issue by labr1005** [modmore/VersionX#110]
This is not about being able to restore a deleted resource with VersionX.

But a log entry when a resource is deleted (OnResourceDelete) could be very usefull IMO. Especially the WHO deleted a resource 😄.

Maybe "Mode" could be "Delete" in this case.

Bonus request: Mode "Undelete" when a resource is being restored (OnResourceUndelete).

**Comment by muzzwood** [comment]
I believe this should be covered by the MODX manager log. If I'm misunderstanding, feel free to reopen!
