### ISSUE TITLE
VersionX integration with Fred

### ISSUE THREAD

**Issue by JANogueira** [modmore/VersionX#112]
Hi Mark,

While using Fred, VersionX does not registers the content change made on the Frontend.
Do you have any plans to create a plugin to integrate VersionX with Fred? Do you know if linking the VersionX plugin with the events `FredOnFredResourceSave` and `FredElementFormRender` will work?

Thanks in advance.

**Comment by Mark-H** [comment]
https://github.com/modxcms/fred/issues/75

**Comment by Mark-H** [comment]
I'm of the opinion that Fred should fire the right event rather than VersionX needing to be adapted.

**Comment by JANogueira** [comment]
Hi Mark,

Ok, I will try this to confirm if works.
Tha is for the tip.

**Comment by Mark-H** [comment]
https://github.com/modxcms/fred/issues/75#issuecomment-549291413

**Comment by Mark-H** [comment]
Added in 2.4.
