### ISSUE TITLE
assets namespace is set wrong

### ISSUE THREAD

**Issue by Jako** [modmore/VersionX#116]
The assets path namespace setting of the 2.3.0 package in the MODX extra repository shows `/Users/mhamstra/Sites/development.local/VersionX/assets/components/versionx/` after it is updated/reinstalled.

**Comment by Mark-H** [comment]
That's not used anywhere but I'll correct that in the next build.

**Comment by Mark-H** [comment]
Fixed in 2.3.2, thanks.
