### ISSUE TITLE
MODX 3.0.1-pl - chunks and snippets versions not saved

### ISSUE THREAD

**Issue by deJaya** [modmore/VersionX#121]
I’ve checked against four different MODX 3.0.1-pl sites and all of them fail to save new versions [via VersionX] when Chunks or Snippets are saved.

Resource versions are saved OK.

When saving a Chunk or Snippet - one or more of the following errors are logged:

`[2022-07-01 20:15:05] (ERROR @ /home/xxyyzz/core/components/versionx/model/versionx.class.php : 318) PHP warning: Object of class MODX\Revolution\mysql\modSnippet could not be converted to int`
`[2022-07-01 20:15:21] (ERROR @ /home/xxyyzz/core/components/versionx/model/versionx.class.php : 279) PHP warning: Object of class MODX\Revolution\mysql\modChunk could not be converted to int`
`[2022-07-01 20:15:21] (ERROR @ /home/xxyyzz/core/components/versionx/elements/plugins/versionx.plugin.php : 117) undefined error`

VersionX is up to date. All sites on PHP 8.1.

**Comment by deJaya** [comment]
[discussion and solutions](https://community.modx.com/t/versionx-and-modx-3-0-1-pl-chunks-and-snippets-versions-not-saved/5530/10)

**Comment by Mark-H** [comment]
Fixed in 2.4
