### ISSUE TITLE
Setup Dialog (Snapshot) misplaced

### ISSUE THREAD

**Issue by exside** [modmore/VersionX#28]
When I install VersionX v2.0rc2 on my 11" MacbookAir, the dialog popup which asks to make snapshots of what is cut off at the bottom (where the OK Button is), I have to manually drag it up a bit to reach the OK button.

This is a detail for sure, just wanted to get it out of my head =)

**Comment by muzzwood** [comment]
This shouldn't be an issue anymore in v3.x. If it is, feel free to reopen.
