### ISSUE TITLE
Ability to add version notes to a version save

### ISSUE THREAD

**Issue by Mark-H** [modmore/VersionX#56]
Either through a version notes field when saving resources/elements, or by adding a note after the fact.

**Comment by jmacdonald-spectacle** [comment]
This would be a very useful feature for me, especially as a landmark for when important changes are made.

As for implementation, an editable grid column would suffice.

**Comment by muzzwood** [comment]
Milestones in VersionX 3.x allow for tags to be set on deltas. Closing!
