### ISSUE TITLE
Reload resource after revert

### ISSUE THREAD

**Issue by SiarAneas** [modmore/VersionX#61]
Hi Mark!
I'm having the following issue (checked it in several browsers - so I hope it isn't just me): When reverting to a previous version the resource isn't reloaded in manager so all fields have still the values from before the revert (though the revert was saved in background).
If the user now clicks on the save button (which gets also enabled after the revert) the old data (from before the revert) is saved again.

Im using Revo 2.2.8 btw - not sure whether this is relevant for this issue.
Cheers,

**Comment by neoneddy** [comment]
+1

**Comment by sebastian-marinescu** [comment]
Hi @Mark-H, 
I could look deeper into this, if you want. 
On the first quick look, I think adding it to the JS success-handler here https://github.com/Mark-H/VersionX2/blob/d575c893260f3e1112fbcb31c0d0e0877cdacee1/assets/components/versionx/js/mgr/resources/grid.resources.js#L123 could be a solution. Also the message should either be updated, or a second message could appear. 

What do you think?

**Comment by muzzwood** [comment]
There is a full page reload for any kind of revert in VersionX 3.x 
Closing!
