### ISSUE TITLE
Hide "Back to Overview" from clients/publishers

### ISSUE THREAD

**Issue by pmacswebteam** [modmore/VersionX#81]
We have hidden VersionX from the top menu bar from our clients, however, they are still able to see the full VersionX overview by clicking the "Back to Overview" button when editing a resource.  Is there a way to hide this button from our clients? We would like to have versioning for all assets, however, we would like to restrict them so that they can only control versioning of their resources, NOT Templates, Template Variables, Chunks, etc.

**Comment by pmacswebteam** [comment]
Any progress on this issue? Help would be greatly appreciated! Thanks!

**Comment by pmacswebteam** [comment]
Hello, 

The issue referenced above (#84) by adamwintle seems to be different from the question that we have posed, and still has yet to be answered.  Could you, or someone, please advise us on how we can hide the "Back to Overview" button.  Ideally, we would want to do this only for publishers, but would be ok if this button was hidden for all users. Thank you.

**Comment by Mark-H** [comment]
Sorry for not answering to this sooner. That's not currently possible, but I'll consider it as a feature request for when I (finally) circle back to building the next version of VersionX.

**Comment by muzzwood** [comment]
In VersionX 3.x everything is contained within the Versions tab which can be disabled via user and user group settings.
Closing!
