### ISSUE TITLE
Feature-Request: Dump-All-Versions data on every formtab

### ISSUE THREAD

**Issue by sebastian-marinescu** [modmore/VersionX#88]
It would be nice to be able to dump all versions of a specific type in the VersionX Action-View.

Use-Cases: 
- Database getting to big 
- Changed a lot and want to start versioning from scratch

What do you think?

**Comment by Mark-H** [comment]
If I were a malicious editor set out to ruin my former employer who just sacked me because I ate all the M&Ms in the break out room, that sounds like a lovely button.

**Comment by sebastian-marinescu** [comment]
Good point and nice use-case for M&Ms :wink:

So then the button should only be visible to the admins or to people with a permission to it. 
But then again, what if an permitted user ate all the M&Ms...

So probably only the admins should see it, because they also most likely have access to the database.
What do you think now? :)

**Comment by muzzwood** [comment]
I think the cleanup solution in v3 handles the db getting too big scenario. As for starting fresh, I don't think that should be a control in the UI, it'd be better to directly truncate the tables.
Closing! 🙏🏻
