### ISSUE TITLE
Reverting deleted resources fails with error

### ISSUE THREAD

**Issue by ghost** [modmore/VersionX#93]
Attempting to revert a resource that has been deleted fails with a generic error:
![image](https://cloud.githubusercontent.com/assets/4050256/25198574/996369c4-250d-11e7-8f20-9700814cf38d.png)

In the MODX error log is the following:
> Unable of setting TV 16 to no

That TV appears to have been deleted so this may not actually be about the resource having been deleted.

**Comment by muzzwood** [comment]
This shouldn't be an issue anymore in v3.
Closing!
