### ISSUE TITLE
Saved On timestamp using wrong timezone

### ISSUE THREAD

**Issue by travisbotello** [modmore/VersionX#97]
I am running VersionX 2.1.3 in MODx Revo 2.6.1. When I check the versions tab all *Saved On* timestamps are showing the wrong timezone. (2 hours behind)

Timezone is set via php.ini to Europe/Berlin, also the server time in MODx is showing the correct time as well as php.ini. When I publish or unpublish a resource MODx it is showing me the correct time. So I assume that VersionX is somehow using a wrong timezone.

Any ideas?

**Comment by muzzwood** [comment]
This shouldn't be an issue in VersionX 3.x
If it is, please feel free to reopen!
