### ISSUE TITLE
Filtering/report summary in grid

### ISSUE THREAD

**Issue by jcdm** [modmore/VersionX#99]
I often use the grid as a way to get a 'report view' of what has been updated since I cloned a site from production for changes/development.

To do this I parse through all updates since the time I performed the clone and manually write a list of unique assets which can appear in the list anywhere from once to dozens of times.

It would be a big help to this workflow to provide a filtering option which only showed the last time each asset was modified so it became a list of 'latest update' times rather than a list of 'any time any asset was ever saved'.

**Comment by SnowCreative** [comment]
That would make the list load faster, too, when there are thousands of edits in the table!

**Comment by muzzwood** [comment]
VersionX 3's manager page has a grid that only shows the latest change for each object. You then need to select the object to dig further into past deltas. I think that covers the request, but if not, feel free to reopen! 😃
